# Site settings
title: Your awesome title
email: julien.venerosy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Julien Venerosy, Intégrateur web. Porfolio, CV, News
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jvenerosy.fr" # the base hostname & protocol for your site
twitter_username: jvenerosy
github_username:  jvenerosy
id_ps4: jvener974

# Build settings
markdown: kramdown
highlighter: rouge