# Site settings
title: JVenerosy
email: julien.venerosy@gmail.com
description: "News"
baseurl: ""
url: ""
paginate: 1
paginate_path: "news/:num"
github: jvenerosy

# Build settings
markdown: kramdown
permalink: /:categories/:title/
highlighter: rouge