# Site settings
title: JVenerosy
email: julien.venerosy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Actus Web, high tech, mobile...
baseurl: "" # the subpath of your site, e.g. /blog/
imgurl: "img/"
url: "http://jvenerosy.fr" # the base hostname & protocol for your site
twitter_username: jvenerosy
github_username:  jvenerosy
id_ps4: jvener974

# Build settings
markdown: kramdown
highlighter: rouge